### ISSUE TITLE
EmbeddingSource wikipedia2vec - ExplicitSemanticAnalysis

### ISSUE THREAD

**Issue by m3ttiw** [m3ttiw/Framework_CBRS_py#37]
Realizzare un implementazione di Explicit semantic analysis con **wikipedia2vec**

**Comment by rbarile17** [comment]
Questa tecnica non può essere utilizzata per apprendere embeddings su un corpus di documenti dato dall'utente(come per le altre), ma apprende gli embedding dei termini che compaiono in un dump di wikipedia.

**Comment by rbarile17** [comment]
Si trovano diversi embedding preaddestrati in questo modo, disponibili in quasi tutte le lingue dato che wikipedia ha articoli multilingua; quindi ritengo inutile inserire questo tool nel framework.
Le altre tecniche sono utili poichè possono essere eseguite su un corpus scelto dall'utente

**Comment by m3ttiw** [comment]
E se questa tecnica restituisse semplicemente gli embedding pre-addestrati per i termini nel nostro corpus?

**Comment by m3ttiw** [comment]
Non avrebbe un comportamento da "Learner" ma da "downloader"

**Comment by rbarile17** [comment]
In questo caso sarebbe una implementazione di una embeddingSource e non di un EmbeddingLearner, ma se non sbaglio(faccio una prova a breve) i modelli di wikipedia2vec possono già essere caricati tramite il loader gensim in modalità word2vec quindi tramite la nostra 
classe(implementazione di EmbeddingSource) BinaryFile.
Quindi la source dei modelli wikipedia2vec é BinaryFile

**Comment by m3ttiw** [comment]
secondo me in questo caso converrebbe tenere separate le due classi, quindi con `wikipedia2vec` come estensione di `EmbeddingSource`

**Comment by rbarile17** [comment]
Ma é un duplicato, lo fa un'altra classe; non serve ripetersi

**Comment by rbarile17** [comment]
Ho provato ad importarlo tramite gensim, ma mi da problemi; creo una source dedicata.
Ho rimosso nel master il file explicit_semantic_analysis.py dalla cartella embedding learner dato che come visto nei commenti precedenti questa tecnica non apprende embedding su collezioni personalizzate, ma su dump di wikipedia
